### ISSUE TITLE
logLevel configuration fails

### ISSUE THREAD

**Issue by mephinet** [Updater/protractor-console#1]
I might be mistaken, but following the documentation, I am unable to change the loglevels to be reported. My protractor configuration is:
`plugins: [
        { package: 'protractor-console',
         logLevels: ['debug', 'info', 'warning', 'severe']
        }
    ],
`
the plugin is executed, but the log-level change is not active:
`Test console output (log levels: warning, severe)`

Could you please take a look whether you can reproduce this behaviour? Thanks!

**Comment by pmowrer** [comment]
Thanks for logging the issue! Protractors plugin system had some breaking changes in 2.2.0, which is what's causing this. Fix underway.

**Comment by pmowrer** [comment]
@mephinet Should be fixed in `2.0.0`.

**Comment by mephinet** [comment]
it is - thanks a lot!
